// <auto-generated />
namespace OptionsWebSite.Migrations.DiplomaOptionsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedChoices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedChoices));
        
        string IMigrationMetadata.Id
        {
            get { return "201603240302359_Seed Choices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
