// <auto-generated />
namespace OptionsWebSite.Migrations.DiplomaOptionsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PleaseWOrk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PleaseWOrk));
        
        string IMigrationMetadata.Id
        {
            get { return "201603250449170_Please WOrk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
